### ISSUE TITLE
Publish docker image egnyte/gitlabform:1

### ISSUE THREAD

**Issue by glensc** [egnyte/gitlabform#173]
I don't feel confident putting "latest" to docker image when setting up CI config.

Following semver should allow breaking changes without breaking my pipeline.

So please publish along with "latest" also tag indicating 1.x versions.

**Comment by gdubicki** [comment]
Good idea!

Will add that on the next occasion.

However note that we care a lot about following the semver and about our users. We won't surprise you with just pushing a incompatible new GitLabForm version to PyPI and DockerHub some day.

The plan for releasing v2.0, where the config syntax will change, is to:
* release pre-releases to PyPI versioned according to [PEP 440](https://www.python.org/dev/peps/pep-0440/) to use the fact that `pip` is smart enough to not install pre-releases when you do plain `pip install gitlabform`, in other words: unless you explicitly request such version, you won't get a pre-release from `pip`,
* similarly pre-releases to DockerHub will NOT get the `latest` tag,
* all v2.0 releases will require a special flag in the config file to indicate that your config is v2.0-compatible, aborting the run with an informative message otherwise (similarly to what we did here: https://github.com/egnyte/gitlabform/blob/fix_157/gitlabform/gitlab/core.py#L61-L75),
...so I'd say that you are pretty safe using `latest` for this app. :)

**Comment by gdubicki** [comment]
I am close to automating assigning tags using a special GitHub Action for another project ([here](https://github.com/voxpupuli/puppetboard/actions/runs/844308077)), so I will do this for GitLabForm too. v1 will get the tag 1 and v2 - 2 and „latest”. :)

**Comment by gdubicki** [comment]
I haven't automated it yet, but for now I have manually added "1" tag to the last v1 release and "2" to the v2 final release.

**Comment by gdubicki** [comment]
Since v.2.1.1 we automatically tag new images with tags like <major_version>, <major_version>.<minor_version> etc. It's all documented in https://hub.docker.com/r/egnyte/gitlabform now. So finally we can close this issue as completely resolved. 😊
