### ISSUE TITLE
Join the conversation around Auto DevOps

### ISSUE THREAD

**Issue by nagyv** [egnyte/gitlabform#192]
Hi!

I'm the GitLab product manager responsible for GitLab's Terraform and Kubernetes Integrations and Auto DevOps.

We plan to re-think how Auto DevOps works to assure that it serves our users requirements better. One of the initial ideas where we could provide a better service to our users is - I think - related to why GitLabForm exists. I have formulated the job statement for Auto DevOps as

> Once I have a stable development and operations organisation, I want to follow DevOps best practices, in order to shorten the feedback loop and enable continuous learning.

As far as I understand, this is partially addressed with GitLabForm, especially when someone sets it up [as webhook for new projects](https://github.com/egnyte/gitlabform/blob/main/docs/AUTOMATE_FOR_NEW_PROJECTS.md).

Would any of you be interested in providing feedback about your own views about what Auto DevOps should be?

**Comment by amimas** [comment]
I have started using GitLabForm recently. I haven't gone as far as "Automation for new projects using webhook" article, yet. I really like this tool because of the "config-as-code" solution.

I'm using a hosted gitlab instance at work. Unlike github.com or gitlab.com, our hosted instance is much more than just an SCM platform for anyone to create projects. We have specific requirements and need audit trail for compliance. GitLab "Audit log" feature is not fully mature yet, in my opinion. But, even if it was, the config-as-code approach provides a familiar process:

- Have a dedicated project that uses this tool (GitLabForm) to manage all or necessary projects
- Open MR for any changes to a project setting
- Review, Approve, and Merge
- CI Pipeline will apply necessary setting change to one or more projects

With this setup:

- nobody really needs (in most cases) `maintainer` level access
- we can have a standard project settings/configs for all the projects
  - some projects may have slightly different settings, if needed
- all changes are traceable with necessary ticket and approval info

This may not fall under "Auto Devops", but thought I'd share my experience and usage in case there are any opportunities. So far I find GitLabForm to be extremely valuable.

**Comment by gdubicki** [comment]
It seems that we don’t have anything more to add, so I will close this to increase visibility of other issues in this repo.
