### ISSUE TITLE
Implement the "protected branches" API endpoint

### ISSUE THREAD

**Issue by born4new** [egnyte/gitlabform#27]
Hey there!

That endpoint would be pretty useful for us, as we want to have a branch on a project that should not be mergeable by anybody...

Sadly, I couldn't find a reference to it in the code. Are you planning on implementing it?

Cheers!

Gitlab Documentation: https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches

**Comment by gdubicki** [comment]
I think that you misunderstood me: it's already implemented in gitlabform and I did it was when this API was not yet deprecated. :)

**Comment by gdubicki** [comment]
Note to self: when implementing this we should take #10 into account.

**Comment by gsemet** [comment]
"Protected tag" as well?

**Comment by gdubicki** [comment]
Sadly I don’t have time to develop this myself currently, but we are open to accepting PRs with this.

**Comment by therealgambo** [comment]
@gsemet - Ive implemented protected tag functionality in #39

**Comment by gdubicki** [comment]
Note to self: we can implement this feature as:
- replacement for the current way of managing branch protection, including different syntax - this would require major version uptick,
- adding new way next to the old way with making the old one use the new API under the hood.

Of course the 2nd is more user-friendly but because we have too little maintainers of this app I would prefer the 1st as it requires less maintenance.

We can prevent the app from running ONLY IF user is using branch protection config and does not declare the config to be compatible with GitLabForm v. 2.*.

After we implement new approvers API in #68 we will probably have to do the same.

Ideally we should do both of these changes together to have only a single major version uptick here.

While creating v.2 we can think about more config syntax improvements. Let's discuss them in a separate issue.
