### ISSUE TITLE
Exit when the first error occurs

### ISSUE THREAD

**Issue by icy** [egnyte/gitlabform#46]
Is it possible to terminate the program on the first error? That would be very useful when using the tool as a CI tool for gitlab per-se.

Current behavior: The program continues event if some error occurs (https://github.com/egnyte/gitlabform/blob/84b7986aacb8417021ed8ea7ee2efcc3e517506b/gitlabform/gitlabform/core.py#L222)

Expected behavior: The program terminates immediately when the first error occurs.

**Comment by gdubicki** [comment]
Hi @icy !

This behaviour is intentional as we have > 80 projects in some groups managed by gitlabform and we did not want the recurring job that sets/restores settings for them break because of a single broken project.

But I would gladly merge a PR that would add a command line switch that would introduce optional, non-default behaviour that you would prefer, something like https://github.com/egnyte/gitlabform/blob/master/gitlabform/gitlabform/core.py#L98 .

**Comment by jcovington16** [comment]
Is this something i can contribute to? I see this issue is still open.

**Comment by gdubicki** [comment]
Sure, @jcovington16 , PRs are welcome.

**Comment by jcovington16** [comment]
Awesome @gdubicki I really do appreciate it. What can I do to help? Or what do you guys need some assistance on that I can take and complete?

**Comment by gdubicki** [comment]
We just need a Pull Request with this feature. :)

**Comment by jcovington16** [comment]
Awesome. I will go ahead and do just that.

**Comment by gdubicki** [comment]
Fixed in #137 , thanks @jcovington16 ! This will be released in the next version, probably within a week or two.

**Comment by gdubicki** [comment]
This has been released in [v.1.18.4](https://github.com/egnyte/gitlabform/releases/tag/v1.18.4). Sorry that forgot to describe this release properly - we fixed it now. :)
