### ISSUE TITLE
Protected branches API not implemented?

### ISSUE THREAD

**Issue by zaitsxl** [egnyte/gitlabform#77]
Hi,

I read the documentation up and down but could not find how to do what described here https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches. Is this not implemented yet? Thanx

**Comment by gdubicki** [comment]
Hi,

This feature is described here: https://github.com/egnyte/gitlabform/blob/master/config.yml#L122-130

Although the GitLab's API has changed much recently, it seems that this is still working.

Please try to use it and let me know!

Sorry if it is not working - I am working on adding integration tests in #72  that will check if we are not loosing some features because of GitLab changes.

**Comment by gdubicki** [comment]
I checked and it is working for me with a current-ish GitLab version, although with less features than the current API provides.

**Comment by gdubicki** [comment]
Closing this in favor of #27 . Please follow that issue @zaitsxl or reopen this ticket you have any issues with using the current feature.

**Comment by zaitsxl** [comment]
Please can you give an example how you supply parameters of these https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches

**Comment by gdubicki** [comment]
You cannot supply these parameters, @zaitsxl , because the current version Protected branches API is not implemented in gitlabform yet. For now gitlabform uses an older API, for which docs are not available online anymore. I have just updated the docs under https://github.com/egnyte/gitlabform/blob/master/config.yml#L122 to show what is possible as of now, please check it out.

**Comment by zaitsxl** [comment]
Okay that's what I was asking initially :) Thanx looking forward for that to be implemented
